import{a as w,S as P,i as u}from"./assets/vendor-DV6r_H9s.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&l(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function l(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const E="50349576-73448956e16d67ea550d7c551",$="https://pixabay.com/api/",O=40;async function m(o,r=1){return(await w.get($,{params:{key:E,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:O,page:r}})).data}const L=document.querySelector(".gallery"),a=document.querySelector(".loading-button");let H=new P(".image-li a",{captionDelay:250,captionsData:"alt"}),p=null;function y(o){const r=o.map(({largeImageURL:i,webformatURL:l,tags:e,likes:t,views:s,comments:S,downloads:q})=>`<li class="image-li">
           <a href="${i}"> 
             <img class="li-img" src="${l}" alt="${e.split(",").slice(0,3).join(",")}" /> 
           </a>
          <div class="div-upper">
            <ul>
              <li><div class="div-inner"><b>Likes</b> ${t}</div></li>
              
              <li><div class="div-inner"><b>Views</b> ${s}</div></li>
              <li><div class="div-inner"><b>Comments</b> ${S}</div></li>
              <li><div class="div-inner"><b>Downloads</b> ${q}</div></li>
            </ul>
          </div>
        </li>`).join("");L.insertAdjacentHTML("beforeend",r),H.refresh()}function x(){L.innerHTML=""}function g(){document.querySelector("#loader").style.display="flex"}function h(){document.querySelector("#loader").style.display="none"}a.addEventListener("click",()=>{typeof p=="function"&&(M(),p())});function D(o){p=o}function A(){a.style.display="block"}function c(){a.style.display="none"}function M(){a.disabled=!0}function b(){a.disabled=!1}let d="",n=1;const v=40;let f=0;document.addEventListener("DOMContentLoaded",()=>{const o=document.querySelector("#search-form");c(),o.addEventListener("submit",async r=>{if(r.preventDefault(),d=o.searchQuery.value.trim(),!!d){n=1,x(),c(),g();try{const i=await m(d,n);if(f=i.totalHits,i.hits.length===0){u.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(i.hits),n*v<f?(A(),b()):c()}catch{u.error({message:"Error fetching images. Please try again later.",position:"topRight"})}finally{h()}}}),D(async()=>{n+=1,M(),g();try{const r=await m(d,n);y(r.hits),n*v>=f?c():b()}catch{u.error({message:"Error loading more images.",position:"topRight"})}finally{h()}})});
//# sourceMappingURL=index.js.map
